# put this file in the root of the project before deploying.

# need sudo for docker (always)
sudo: required

language: generic

services:
  - docker

before_install:
  # need to move into the project folder before we do anything.
  - cd frontend
  # we are running Dockerfile.dev to test run tests. Convention: name/image_name
  - docker build -t ravi/frontend-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend-dev npm run test -- --coverage

# we deploy Dockerfile to AWS
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  # what you name ins AWS elastic beanstalk.
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: "insert name of the bucket"
#  # same as app name
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
