# need sudo for docker (always)
sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t frontend-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend-dev npm run test -- --coverage