version: '3.7'
services:
  minio:
    build:
      dockerfile: Dockerfile
      context: ./minio
    volumes:
      - .minio/data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data